### ISSUE TITLE
Version 2.0 Stream Pi Linux Arm x32 Missing Java Files

### ISSUE THREAD

**Issue by leappad** [stream-pi/client#104]
I was installing the experimental 2.0 version for my raspberry pi (since it's the only updated version that works with my pc) and I got a massive error when launching it in the console that I was missing important Java files here's the screenshot 
![image](https://user-images.githubusercontent.com/77120963/148323432-88d77ffc-087f-4875-a79f-951adb24a9e5.png)

**Comment by rnayabed** [comment]
which raspberry pi ? which OS?

**Comment by leappad** [comment]
> 

It's a raspberry pi 4 running raspbian

**Comment by leappad** [comment]
I tried using the updated version and I think it may have fixed the issue but now I have to enable some sort of driver how would I do this? 
![image](https://user-images.githubusercontent.com/77120963/150653774-b62203df-5978-4665-b04b-dbb2f34b5132.png)

**Comment by rnayabed** [comment]
The latest snapshot should now work on ARM 32. Tested on Raspberry Pi 0 W with Raspbian bullseye.
