### ISSUE TITLE
Android APK installation fails on 3 different devices

### ISSUE THREAD

**Issue by mngarchow** [stream-pi/client#106]
Installation of the APK failed to three different Android devices that meet the stated minimum requirements (64-bit ARM processor and version 5.0+).

Device 1:
Moto G5 plus ([Specifications](https://www.gsmarena.com/motorola_moto_g5_plus-8453.php))
Chipset: Qualcomm MSM8953 Snapdragon 625 (14 nm)
CPU: Octa-core 2.0 GHz Cortex-A53
Android version 8.1
Client 1.0.0 EA 3

After copying the file to the phone, I clicked on the file in the default file manager. I was prompted with "Your phone and personal data are more vulnerable.... loss of data that may result form its use." I clicked Continue. I was then taken to a screen that said "Do you want to install this application? It does not require any special access". I clicked Install. After a brief progress bar the next screen said "App not installed.". The only option was to click Done.

Device 2:
Samsung Galaxy J7 SM-J700T ([Specifications](https://www.gsmarena.com/samsung_galaxy_j7-7185.php#j700t))
Chipset: Qualcomm MSM8939 Snapdragon 615
CPU: Octa-core (4x1.4 GHz Cortex-A53 & 4x1.0 GHz Cortex-A53)

Android version 7.1.1
Client 1.0.0 EA 3 

First I enabled the "Unknown Sources" toggle on Lock Screen and Security in Settings. After copying the file to the phone, I clicked on the file in the default file manager. I was then taken to a screen that said "Do you want to install this application? It does not require any special access". I clicked Install. After a brief progress bar the next screen said "App not installed. This app isn't compatible with your phone." The only option was to click Done.

Device 3:
Samsung Galaxy Tab A ([Specifications](https://www.gsmarena.com/samsung_galaxy_tab_a_8_0_(2015)-7121.php))

Experience, same as device 2.

I am unsure if the minimum requirements are outdated or if this is an actual bug. Thanks!

**Comment by MartinRome** [comment]
My Fire tablet HD 8 does the same as your Device 1. 

>After copying the file to the phone, I clicked on the file in the default file manager. I was prompted with "Your phone and personal data are more vulnerable.... loss of data that may result form its use." I clicked Continue. I was then taken to a screen that said "Do you want to install this application? It does not require any special access". I clicked Install. After a brief progress bar the next screen said "App not installed.". The only option was to click Done.

Client 1.0.0 EA 3

Android ver.  9

**Comment by rnayabed** [comment]
This is most likely because your devices are 32 bit, or are 64 bit systems powered by 32 bit OS. 

To confirm, please download a terminal emulator like termux, and run `uname -a`. You may also refer to system info apps like cpuz which provide the supported ABIs and architecture for your device.

**Comment by mngarchow** [comment]
> This is most likely because your devices are 32 bit, or are 64 bit systems powered by 32 bit OS.
> 
> To confirm, please download a terminal emulator like termux, and run `uname -a`. You may also refer to system info apps like cpuz which provide the supported ABIs and architecture for your device.

Thanks, CPU-Z says the kernel is Armv7l, which seems to conflict with what I found on the official motorola site. Bummer, your project would have been a great use for older devices.

**Comment by MartinRome** [comment]
> To confirm, please download a terminal emulator like termux, and run uname -a.

on my fire 8 it's 
> armv8l

CPUz says 
> it's an ARM vortex-A53

which from what i can gather online is a 64bit CPU.

**Comment by rnayabed** [comment]
@MoronPhatboi looks like amazon blocks debug apk installation on their tablets.

Follow these steps:

https://developer.amazon.com/docs/fire-tablets/webapp-use-debug-apk.html
