### ISSUE TITLE
Unable to connect Raspberry Pi 400 to windows 10

### ISSUE THREAD

**Issue by ajamesm819** [stream-pi/client#107]
PC running wired and wireless
Tried disabling ethernet port, only using wifi, same 5Ghz connection
Tried using different port
Still unable to connect raspberry pi client to windows server
![streampi issue 1](https://user-images.githubusercontent.com/97810387/149639368-8741ada8-71f3-4bad-b597-2530fbf5f977.png)
![streampi issue 2](https://user-images.githubusercontent.com/97810387/149639370-8e804f7d-59f8-4fa1-93ae-54132842a634.png)

**Comment by rnayabed** [comment]
This looks like an issue with your network. Can you once try connecting your pi from PC via SSH?

**Comment by ajamesm819** [comment]
I'll try that and get back to you!

**Comment by sebggph** [comment]
Are there any recommendations to configure Win10 to get the connection right.. 
Having the same issue. I am running the server on Win10 and setting up a client on a Raspberry pi 4.
The client can't connect.

I can connect over SSH to my raspberry from the win 10.
Sharing is on for public and private networks on my win 10 computer at this moment.

Thank you in advance

**Comment by rnayabed** [comment]
Closing since user has not replied for over a month.
