### ISSUE TITLE
Add more fine-grained setting's options to the settings menu

### ISSUE THREAD

**Issue by TOGLK** [stream-pi/client#22]
Divide up the layout of the "Setting's" menu to make things easier for the end-user to follow, and to make the many different settings that are available easier to identify, and subsequently modify. 

=========================

How would this be achieved?

So, first you would have "General" settings, this would include:
"Nick Name", "Current Profile", "Start On Boot", &, "Show Cursor".

=========================

Next you would have "Network Settings", which would include the following sections:
"Host Name/IP", &, "Port".
Other future networking related settings would also go here.

=========================

The third section would be for "Graphical" settings, and it would include:
"Current Theme" (Currently just called "Theme". I would change it.), "Full Screen", "Screen Height", &, "Screen Width".

=========================

The last section would be for "Miscellaneous" settings, and this would include the options for:
"Theme's Path", "Icon's Path", &, "Profile's Path".

=========================

The options to: "Disconnect", "Save", "Exit", &, "Close", would be accessible from the bottom of all the various "Settings" sections.

Other modifications I would look to add is an option to "Export" & "Import" settings configuration files from within the "Miscellaneous" settings menu.

And another modification I would make is the ability to "Reset to Defaults" on a "per-section" basis instead of globally, this provides the end-user with greater control.

**Comment by rnayabed** [comment]
This has been implemeneted
