### ISSUE TITLE
Remove all of the tags from the client releases

### ISSUE THREAD

**Issue by SamuelQuinones** [stream-pi/client#26]
I have deleted all of the releases but the tags remain.

follow this [guide](https://wptheming.com/2011/04/add-remove-github-tags/) to delete the tags, it looks like you'll need to do it locally

**Comment by abhinayagarwal** [comment]
A much easier way...

Fetch all remote tags from remote:

`git fetch --tags <remote-name>`

Delete all tags in remote:

`git push <remote-name> --delete $(git tag -l)`

**Comment by rnayabed** [comment]
> A much easier way...
> 
> Fetch all remote tags from remote:
> 
> `git fetch --tags <remote-name>`
> 
> Delete all tags in remote:
> 
> `git push <remote-name> --delete $(git tag -l)`

thanks, will do that asap

**Comment by rnayabed** [comment]
done
