### ISSUE TITLE
[BUG] Figure out fix for overscan on Raspberry Pi Screens

### ISSUE THREAD

**Issue by SamuelQuinones** [stream-pi/client#27]
This issue was brought up by @Brady-StreamPi so if I'm missing anything else he can leave a comment.

This issue happens on multiple types of screens, apparently the buttons overscan over the screen, meaning something isn't quite right when the client adjusts to the resolution of the screen.

**Comment by rnayabed** [comment]
fixed

**Comment by SamuelQuinones** [comment]
FIX:
the current EA has no first time startup dialog so by default it thinks your screen to be of 1024*600,
now the new system first launches the first time setup pane in 300*300 which shohld be enough for most displays
