### ISSUE TITLE
Create ".exe" files for all Windows x86 versions of Stream-Pi [Client]

### ISSUE THREAD

**Issue by TOGLK** [stream-pi/client#37]
Currently the "Stream-Pi Server" & "Stream-Pi Client" builds for Windows x86 platforms are distributed as a "VBScript" inside of a zipped folder structure.

This does not make for a user-friendly experience and it creates additional support requirements for end-users that could otherwise be completely eradicated if we simply released the program as a ".exe" file for the Windows x86 platform.

**Comment by SamuelQuinones** [comment]
Not possible now due to limitations to `jpackage`. Will be done in the future

**Comment by rnayabed** [comment]
This is possible
