### ISSUE TITLE
Add ToggleAction

### ISSUE THREAD

**Issue by rnayabed** [stream-pi/client#42]

**Comment by TOGLK** [comment]
Shouldn't this issue be merged with the issue in the "Essential Actions" repository?
Especially as the issue relates to any "Essential Actions" action.

**Comment by rnayabed** [comment]
> Shouldn't this issue be merged with the issue in the "Essential Actions" repository?
> Especially as the issue relates to any "Essential Actions" action.

nope, it includes massive changes to be done within client,server,actionapi

**Comment by rnayabed** [comment]
done
