### ISSUE TITLE
[Android] [Feature Request] Add Haptic Feedback/Vibration When Button is Pressed

### ISSUE THREAD

**Issue by tony199555** [stream-pi/client#46]
What Platform is targeted?:
Android/Any Other Supported Platform

Is this a Bug-Fix, Feature Request, or, Other?:
Feature Request

Describe the issue:
It would be nice if it gives some feedback when a button is pressed. While I was testing, it happened a few times I slide my finger instead of press firmly, and without feedback, I was not able to notice the action has not triggered.

What resolution do you suggest?:
Add haptic feedback or vibration when the button is pressed/ action is triggered.

What other things should be considered?:

**Comment by rnayabed** [comment]
[Done](https://github.com/stream-pi/client/commit/3c9b2b13eeba87b75f864d6441efb82998f6c699)
