### ISSUE TITLE
[Linux] [Feature Request] Add action to trigger "connect to obs websocket"

### ISSUE THREAD

**Issue by sranjb2** [stream-pi/client#47]
Currently there is a "connect at startup" button available within the settings, but if we are using hotkey actions to launch OBS then there is way to connect to obs without entering settings manually. QoL update

**Comment by TOGLK** [comment]
> Good idea

Could you please update the "Title" of the issue to reflect the "Cross-Platform" sate of the suggested [Feature Request]?
Also, Does this not belong in the `Stream-Pi/ Server` repository as this would be a Server-Side change and not a Client-Side change?

**Comment by rnayabed** [comment]
> > Good idea
> 
> Could you please update the "Title" of the issue to reflect the "Cross-Platform" state of the suggested [Feature Request]?
> It would not be limited to only [Linux], and so the "Title' should reflect that.
> Also, Does this not belong in the `Stream-Pi/ Server` repository as this would be a Server-Side change and not a Client-Side change?

Youre right. ill close this issue, can you create a similar one please and add it on server issues?
