### ISSUE TITLE
Support for 32-bit windows

### ISSUE THREAD

**Issue by ubrderechte** [stream-pi/client#48]
Hi Stream-Pi,

first of all thank you to you all to do such a beautiful and helpful plugin.

I have a suggestion for you to improve your project.

Could you release the client version on Windows in 32 bit in future? Because few peoples have old Windows tablets and these are most on 32 bit and I never use this tablet because it's too slow to do big stuff but for small stuff like Stream-Pi it would be perfect.

I know 32 bit is outdated but 32 bit will work on 64 bit and lot of programs are based on 32 bit.

I would appreciate that and maybe more people are thankful if they use it for their low-spec tablets.

Thanks guys and keep it up.

Greetings from Germany
Braveen

**Comment by rnayabed** [comment]
Yes this is possible. It will be available from next release
