### ISSUE TITLE
No fullscreen on my raspberry oled touch display

### ISSUE THREAD

**Issue by phdemartin** [stream-pi/client#56]
Is it posible to have a borderless windows wihout header bar o a fullscreen for the client on raspberry ?

**Comment by rnayabed** [comment]
Yes. Just open streampi settings on the client (cog at the bottom right), and enable the full screen toggle.

**Comment by phdemartin** [comment]
Perfect, I di not seen at first the fullscreen button, my sceen is only 800x600, it vas outside of the view.
Thank you

**Comment by rnayabed** [comment]
@phdemartin can you provide a link to your screen? I am personally interested in an OLED touch display for Pi.

**Comment by phdemartin** [comment]
@rnayabed  This is mine screen https://www.aliexpress.com/item/1005001709776554.html?spm=a2g0s.9042311.0.0.43864c4d8jo2zp
