### ISSUE TITLE
Folder leave button

### ISSUE THREAD

**Issue by DonaldDucker34** [Stream-Pi/Client#6]
I really like what you programmed but you forgot something when i put a folder on my button and i go into the folder i cant get out so you should program another button to get back to the homepage :)

**Comment by dubbadhar** [comment]
You need to swipe from left to right, or from "Return to parent" button, which can be enabled in settings.

Closing for now, reopen if the same problem persists :)

**Comment by DonaldDucker34** [comment]
thanks for the fast answer safed my life xd
