### ISSUE TITLE
Cannot launch client on DietPi installation

### ISSUE THREAD

**Issue by aoconnor-ufl** [stream-pi/client#65]
Followed the steps at https://github.com/stream-pi/client/releases but I get a "jre/bin/java: No such file or directory" error whenever attempting to execute run_console or run_desktop

**Comment by rnayabed** [comment]
Can you provide the directory listing of ur client folder ? (from where you are running run_console or desktop?)
also try again by first `cd` ing into the directory and then run the scripts

**Comment by aoconnor-ufl** [comment]
The directory is "~/Desktop/StreamPi" with all the files unzipped into there.  I've cd into that directory and then executed "./run_console" or desktop as appropriate.

**Comment by aoconnor-ufl** [comment]
What is the architecture and version of the bundled Java?  I am running 64-bit DietPi OS on a Raspberry Pi Model 3B+.

**Comment by rnayabed** [comment]
there are ARMv7 builds (for raspberry pi os). You should try using 32 bit raspberry pi os instead. Arm64 bit builds will be available from next release

**Comment by aoconnor-ufl** [comment]
Ah-ha!  Yes, it was the OS architecture.  I just installed the necessary dependencies for armhf, and it's working!  Looking forward to the arm64 build.
