### ISSUE TITLE
Possibility of a 32 bit build for Linux?

### ISSUE THREAD

**Issue by Interknet** [stream-pi/client#69]
Is there any chance of a 32 bit build on Linux? Understandable if not, would be nice to know however so I could get to installing 64 bit somehow although I'm not entirely confident that would work on the tablet given my last attempts.

While I'm here, thanks for this project - very useful stuff!

**Comment by rnayabed** [comment]
Yes, there will 32 bit builds for linux/windows available from the next release.

However, there wont be 32-bit support for android/iOS, since GraalVM currently does not support 32 bit for native image.

**Comment by Interknet** [comment]
Shame about the other platforms, but look forward to the next release thanks!
