### ISSUE TITLE
No version for android 32 bit.

### ISSUE THREAD

**Issue by epicsucks** [stream-pi/client#79]
I'm just wondering If you can provide a 32 bit android version, or tell me whether I can can recompile it myself for 32 bit.
I tested it out in bluestacks, and it looks really good, but then I realized it won't work on my actual device.

**Comment by rnayabed** [comment]
Unfortunately, this is not possible. Graalvm native image has no 32 bit Android support.

**Comment by epicsucks** [comment]
Oh, too bad. I guess I'll have to look for something else.
