### ISSUE TITLE
rpi4 failed to add service

### ISSUE THREAD

**Issue by Robertcop84** [Stream-Pi/Client#8]
After installing and then running the line sudo /home/pi/StreamPi/start_streampi the script fails to add some service after the line load library glass monocle succeeds.

**Comment by dubbadhar** [comment]
Follow this https://youtu.be/NzzsD__YZE0

**Comment by dubbadhar** [comment]
change the content of your `start_streampi` file to this :

```
#!/usr/bin/env bash
cd /home/pi/StreamPi/
sudo jre/bin/java -Djavafx.platform=gtk -Dcom.sun.javafx.isEmbedded=true -Dcom.sun.javafx.touch=true -Dcom.sun.javafx.virtualKeyboard=javafx -jar StreamPiClient-0.6.jar
```

**Comment by Robertcop84** [comment]
Works, thx!!
