### ISSUE TITLE
Raspberry client - Getting "Failed at readUTF" after upgrading to Windows 11

### ISSUE THREAD

**Issue by ezerusso** [stream-pi/client#80]
Hi,

After upgrading my PC to win11 preview edition, I am getting an error at the Raspberry client stating: **"Alert - Accidentally disconnected from Server! (Failed at readUTF)".**

**> On the server (pc) side the last line I read is:**

------------------------------------------------------------------------------------------------------------------------

> Jul 01, 2021 7:45:38 AM com.stream_pi.server.connection.MainServer run
> INFO: Starting server on port 2005 ...
> Jul 01, 2021 7:45:54 AM com.stream_pi.server.connection.MainServer run
> INFO: New client connected (/192.168.0.215:35184) !
> Jul 01, 2021 7:45:54 AM com.stream_pi.server.connection.ClientConnection initAfterConnectionQuerySend
> INFO: Asking client details ...

------------------------------------------------------------------------------------------------------------------------

Is there something I should try downgrading on my server side to see if I recover compatibility? maybe Java or something?

Thanks in advance and congrats for such a good development!

**Comment by rnayabed** [comment]
Send both client and server log. They are inside the `Stream-Pi` folder in home directory of user.

Also which version are you using?

**Comment by ezerusso** [comment]
Sure!

Server - version 1.0.0 - Windows - Early access.

Client: 1.0.0 - Linux Early Access.
Java 11.0.11 | JavaFX 17-internal

[streampi-server.log](https://github.com/stream-pi/client/files/6748506/streampi-server.log)
[stream-pi-client.log](https://github.com/stream-pi/client/files/6748507/stream-pi-client.log)

**Comment by ezerusso** [comment]
This is the deepest I get with the erorr:

[Thread-3] :: com.stream_pi.client.connection.Client @ run -> :SEVERE = com.stream_pi.util.comms.Message; local class incompatible: stream classdesc serialVersionUID = 1544200817378119061, local class serialVersionUID = 2004200019671976

**Comment by rnayabed** [comment]
This is happening because you're using different versions of streampi client/server together, which isn't supported


Use both EA+3 server and client

It looks either server or client is EA+2
________________________________

**Comment by rnayabed** [comment]
Most probably the client you're using is ea+2 while the server is ea+3

**Comment by ezerusso** [comment]
Yes Sir, it solved by upgrading the Server side installation. Thank you for your time.
