### ISSUE TITLE
Is usable using RPI1?

### ISSUE THREAD

**Issue by ezar** [stream-pi/client#86]
I'm trying to use in RPI1 and after 10 minutes doesn't start :(

**Comment by rnayabed** [comment]
Have you tried running it using desktop mode? There is a bug in the drm driver that prevents it to run on ARMv6 devices like Pi 0 and 1, hence desktop mode is the way to go on these devices

**Comment by rnayabed** [comment]
Stream-Pi Client should work on RPi 1, but only with desktop mode. 

Console mode on RPi 1 is not supported at the moment.
