### ISSUE TITLE
Closing client

### ISSUE THREAD

**Issue by fuzebox1** [Stream-Pi/Client#9]
Why cant i close the client after i've started it? It's fullscreen and doesn't accept any common keybinds for exiting..? Right now i have to cut power to the Pi to exit.

**Comment by dubbadhar** [comment]
Yeah that's a stupid problem (I'm dumb to not reinclude it after removing it for a brief for mobile devices). Use 0.0.5 (then downgrade to 0.0.5 server as well) if you really need that close button

**Comment by fuzebox1** [comment]
I cant seem to run the server on linux, is it only for windows?

**Comment by dubbadhar** [comment]
https://github.com/dubbadhar/streampi_server/releases/tag/0.0.5

**Comment by dubbadhar** [comment]
Since we are reworking on the server, the [new repo](https://github.com/Stream-Pi/Server) doesn't have any releases.
