### ISSUE TITLE
Screen saver shut down screen

### ISSUE THREAD

**Issue by Zykino** [stream-pi/client#90]
On Raspberry Pi, in console mode, if I am not using stream-pi I want the (official) screen to be shut down. Not just a bright black screen.

**Comment by Zykino** [comment]
As requested on discord

```sh
pi@zykino-smartipi2:~ $ ls -l /sys/class/backlight/rpi_backlight/bl_power
-rw-r--r-- 1 root root 4096 Sep 21 19:55 /sys/class/backlight/rpi_backlight/bl_power
pi@zykino-smartipi2:~ $ cat /sys/class/backlight/rpi_backlight/bl_power         1
pi@zykino-smartipi2:~ $ kak screen.sh
pi@zykino-smartipi2:~ $ sudo ./screen.sh
pi@zykino-smartipi2:~ $ cat /sys/class/backlight/rpi_backlight/bl_power
0
pi@zykino-smartipi2:~ $ cat screen.sh
#/bin/env sh

echo 0 > /sys/class/backlight/rpi_backlight/bl_power # changed 0 to 1 before
```
When I set/read 0, the screen is ON. 1 means OFF. Just like this website is describing (the sudo tee hack works as good as creating my shell script). https://scribles.net/controlling-display-backlight-on-raspberry-pi/
Since I only have the official screen connected I tried the website’s proposed command to detect the screen type:
```sh
pi@zykino-smartipi2:~ $ tvservice -s
state 0x400000 [LCD], 800x480 @ 60.00Hz, progressive
```

Note: I saw the similar path but I am unsure how to use this (and if it is possible anyway since I do not found a lot online):
```sh
pi@zykino-smartipi2:~ $ ls -l /sys/class/backlight/rpi_backlight/power/
total 0
-rw-r--r-- 1 root root 4096 Sep 21 19:57 autosuspend_delay_ms
-rw-r--r-- 1 root root 4096 Sep 21 19:57 control
-r--r--r-- 1 root root 4096 Sep 21 19:57 runtime_active_time
-r--r--r-- 1 root root 4096 Sep 21 19:57 runtime_status
-r--r--r-- 1 root root 4096 Sep 21 19:57 runtime_suspended_time
pi@zykino-smartipi2:~ $ cat /sys/class/backlight/rpi_backlight/power/*
cat: /sys/class/backlight/rpi_backlight/power/autosuspend_delay_ms: Input/output error
auto
0
unsupported
0
```

**Comment by rnayabed** [comment]
Can you once disconnect your screen, reboot and then report the output of 

`ls -l /sys/class/backlight/` 

And

`ls -l /sys/class`

**Comment by Zykino** [comment]
```sh
pi@zykino-smartipi2:~ $ ls -l /sys/class
total 0
drwxr-xr-x 2 root root 0 Sep 21 20:17 backlight
drwxr-xr-x 2 root root 0 Sep 21 20:17 bcm2708_vcio
drwxr-xr-x 2 root root 0 Sep 21 20:17 bcm2835-gpiomem
drwxr-xr-x 2 root root 0 Sep 21 20:17 bdi
drwxr-xr-x 2 root root 0 Sep 21 20:17 block
drwxr-xr-x 2 root root 0 Sep 21 20:17 bluetooth
drwxr-xr-x 2 root root 0 Sep 21 20:17 bsg
drwxr-xr-x 2 root root 0 Sep 21 20:17 devcoredump
drwxr-xr-x 2 root root 0 Sep 21 20:17 devlink
drwxr-xr-x 2 root root 0 Sep 21 20:17 dma
drwxr-xr-x 2 root root 0 Sep 21 20:17 dma_heap
drwxr-xr-x 2 root root 0 Sep 21 20:17 drm
drwxrwx--- 2 root gpio 0 Sep 21 20:17 gpio
drwxr-xr-x 2 root root 0 Sep 21 20:17 graphics
drwxr-xr-x 2 root root 0 Sep 21 20:17 hidraw
drwxr-xr-x 2 root root 0 Sep 21 20:17 hwmon
drwxr-xr-x 2 root root 0 Sep 21 20:17 i2c-adapter
drwxr-xr-x 2 root root 0 Sep 21 20:17 ieee80211
drwxr-xr-x 2 root root 0 Sep 21 20:17 input
drwxr-xr-x 2 root root 0 Sep 21 20:17 iscsi_connection
drwxr-xr-x 2 root root 0 Sep 21 20:17 iscsi_endpoint
drwxr-xr-x 2 root root 0 Sep 21 20:17 iscsi_host
drwxr-xr-x 2 root root 0 Sep 21 20:17 iscsi_iface
drwxr-xr-x 2 root root 0 Sep 21 20:17 iscsi_session
drwxr-xr-x 2 root root 0 Sep 21 20:17 iscsi_transport
drwxr-xr-x 2 root root 0 Sep 21 20:17 leds
drwxr-xr-x 2 root root 0 Sep 21 20:17 lirc
drwxr-xr-x 2 root root 0 Sep 21 20:17 mdio_bus
drwxr-xr-x 2 root root 0 Sep 21 20:17 mem
drwxr-xr-x 2 root root 0 Feb 14  2019 misc
drwxr-xr-x 2 root root 0 Sep 21 20:17 mmc_host
drwxr-xr-x 2 root root 0 Sep 21 20:17 net
drwxr-xr-x 2 root root 0 Sep 21 20:17 power_supply
drwxr-xr-x 2 root root 0 Sep 21 20:17 pwm
drwxr-xr-x 2 root root 0 Sep 21 20:17 raw
drwxr-xr-x 2 root root 0 Sep 21 20:17 rc
drwxr-xr-x 2 root root 0 Sep 21 20:17 regulator
drwxr-xr-x 2 root root 0 Sep 21 20:17 rfkill
drwxr-xr-x 2 root root 0 Sep 21 20:17 rtc
drwxr-xr-x 2 root root 0 Sep 21 20:17 scsi_device
drwxr-xr-x 2 root root 0 Sep 21 20:17 scsi_disk
drwxr-xr-x 2 root root 0 Sep 21 20:17 scsi_host
drwxr-xr-x 2 root root 0 Sep 21 20:17 sound
drwxr-xr-x 2 root root 0 Sep 21 20:17 spi_master
drwxr-xr-x 2 root root 0 Sep 21 20:17 spi_slave
drwxr-xr-x 2 root root 0 Sep 21 20:17 thermal
drwxr-xr-x 2 root root 0 Feb 14  2019 tty
drwxr-xr-x 2 root root 0 Sep 21 20:17 uio
drwxr-xr-x 2 root root 0 Sep 21 20:17 vc
drwxr-xr-x 2 root root 0 Sep 21 20:17 vchiq
drwxr-xr-x 2 root root 0 Sep 21 20:17 vc-mem
drwxr-xr-x 2 root root 0 Sep 21 20:17 video4linux
drwxr-xr-x 2 root root 0 Sep 21 20:17 vtconsole
drwxr-xr-x 2 root root 0 Sep 21 20:17 watchdog

pi@zykino-smartipi2:~ $ ls -l /sys/class/backlight/
total 0
```

**Comment by rnayabed** [comment]
So when there is no official display attached, there will be no `rpi_backlight` `sys/class/backlight/` folder

**Comment by Zykino** [comment]
Apparently yes

**Comment by rnayabed** [comment]
latest commit does some work in this scenario. However Since i do not have the official screen myself, its untested and you need to test it yourself

Run this command:

```
curl -sSL https://install.stream-pi.com/client/raspberry-pi | bash -s -- -d https://github.com/stream-pi/client/releases/download/1.0.0-EA%2B4-SNAPSHOT/stream-pi-client-linux-arm32-1.0.0-EA+4-SNAPSHOT-executable.zip
```

You should not manually extract and replace because the new script now does some necessary work to modify permissions to allow Stream-Pi to edit the backlight power state.

**Comment by rnayabed** [comment]
After fresh install, reboot, and then try using the screen saver feature on your official display. Then check whether the screen saver works and what happens to your screen. Regardless of whether it works or not, please share your client log as well.

I also discovered that you can [also edit the brightness of the display](https://raspberrypi.stackexchange.com/a/46229) and not just turn the backlight off or on. However, this is a bit tricky to make sure that it works perfectly since I do not know if there is any way to detect the version of the Raspberry Pi Screen since this does not work well on v1.0 of the official display. We could also offer 2 different ways that user can choose.

**Comment by Zykino** [comment]
I may have changed my hostname with `raspi-config` without restarting before using the command you gave me. Hope nothing was broken :sweat_smile:
```
WARNING: You cannot run Stream-Pi Client as desktop mode while you are in console mode, and vice versa.
Restarting in 10 seconds ...
sudo: unable to resolve host raspberrypi: Name or service not known
```

Hope you were talking about this log file (the console did spam waaaaayy too much).
```sh
pi@smartipi2:~ $ cat Stream-Pi/stream-pi-client.log
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ registerThemes -> :INFO = Loading themes ...
[JavaFX Application Thread] :: com.stream_pi.util.xmlconfighelper.XMLConfigHelper @ getProperty -> :WARNING = CANNOT get property info.website!
[JavaFX Application Thread] :: com.stream_pi.theme_api.Themes @ loadThemes -> :INFO = Added com.stream_pi.defaulthighcontrast to themes!
[JavaFX Application Thread] :: com.stream_pi.util.xmlconfighelper.XMLConfigHelper @ getProperty -> :WARNING = CANNOT get property info.website!
[JavaFX Application Thread] :: com.stream_pi.theme_api.Themes @ loadThemes -> :INFO = Added com.stream_pi.defaultlight to themes!
[JavaFX Application Thread] :: com.stream_pi.util.xmlconfighelper.XMLConfigHelper @ getProperty -> :WARNING = CANNOT get property info.website!
[JavaFX Application Thread] :: com.stream_pi.theme_api.Themes @ loadThemes -> :INFO = Added com.stream_pi.defaultdark to themes!
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ registerThemes -> :INFO = ...Themes loaded successfully !
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = Applying default theme ...
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = Applying theme 'com.stream_pi.defaultlight' ...
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = ... Done!
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = ... Done!
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyGlobalDefaultStylesheet -> :INFO = Found global default style sheet. Adding ...
[Thread-5] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
[Thread-5] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
[Thread-5] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = Applying default theme ...
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = Applying theme 'com.stream_pi.defaultlight' ...
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = ... Done!
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = ... Done!
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyGlobalDefaultStylesheet -> :INFO = Found global default style sheet. Adding ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loading profiles ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loaded all profiles!
[pool-2-thread-1] :: com.stream_pi.client.connection.Client$1 @ call -> :INFO = Trying to connect to server at [my server local ip:port]
[pool-2-thread-1] :: com.stream_pi.client.controller.Controller @ handleMinorException -> :SEVERE = Unable to connect to server. Please check settings and connection and try again.
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = Applying default theme ...
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = Applying theme 'com.stream_pi.defaultdark' ...
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = ... Done!
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = ... Done!
[JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyGlobalDefaultStylesheet -> :INFO = Found global default style sheet. Adding ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loading profiles ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loaded all profiles!
[JavaFX Application Thread] :: com.stream_pi.client.controller.ScreenSaver @ <init> -> :INFO = Is Rpi Screen detected ? true
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loading profiles ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
[JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loaded all profiles!
[JavaFX Application Thread] :: com.stream_pi.client.controller.Controller @ onCloseRequest -> :INFO = Shut down
```

*It worked!* A slider to adjust the brightness is always welcome, but a one time command like so is enough for me. (You can close the issue I think.)
```sh
pi@smartipi2:~ $ cat /sys/class/backlight/rpi_backlight/brightness
255
pi@smartipi2:~ $ echo 100 | sudo tee /sys/class/backlight/rpi_backlight/brightness
100
```

**Comment by Zykino** [comment]
I hope this is unrelated, but on this version I am not able to set actions form the server. Changing the profile worked (number of actions and space between).

Maybe I need to use a corresponding version of the server :thinking:

**Comment by rnayabed** [comment]
Yes. The latest server client builds were changed rapidly. Entire grid system was changed to allow custom sized individual actions

**Comment by rnayabed** [comment]
> I may have changed my hostname with `raspi-config` without restarting before using the command you gave me. Hope nothing was broken 😅
> 
> ```
> WARNING: You cannot run Stream-Pi Client as desktop mode while you are in console mode, and vice versa.
> Restarting in 10 seconds ...
> sudo: unable to resolve host raspberrypi: Name or service not known
> ```
> 
> Hope you were talking about this log file (the console did spam waaaaayy too much).
> 
> ```shell
> pi@smartipi2:~ $ cat Stream-Pi/stream-pi-client.log
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ registerThemes -> :INFO = Loading themes ...
> [JavaFX Application Thread] :: com.stream_pi.util.xmlconfighelper.XMLConfigHelper @ getProperty -> :WARNING = CANNOT get property info.website!
> [JavaFX Application Thread] :: com.stream_pi.theme_api.Themes @ loadThemes -> :INFO = Added com.stream_pi.defaulthighcontrast to themes!
> [JavaFX Application Thread] :: com.stream_pi.util.xmlconfighelper.XMLConfigHelper @ getProperty -> :WARNING = CANNOT get property info.website!
> [JavaFX Application Thread] :: com.stream_pi.theme_api.Themes @ loadThemes -> :INFO = Added com.stream_pi.defaultlight to themes!
> [JavaFX Application Thread] :: com.stream_pi.util.xmlconfighelper.XMLConfigHelper @ getProperty -> :WARNING = CANNOT get property info.website!
> [JavaFX Application Thread] :: com.stream_pi.theme_api.Themes @ loadThemes -> :INFO = Added com.stream_pi.defaultdark to themes!
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ registerThemes -> :INFO = ...Themes loaded successfully !
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = Applying default theme ...
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = Applying theme 'com.stream_pi.defaultlight' ...
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = ... Done!
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = ... Done!
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyGlobalDefaultStylesheet -> :INFO = Found global default style sheet. Adding ...
> [Thread-5] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
> [Thread-5] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
> [Thread-5] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = Applying default theme ...
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = Applying theme 'com.stream_pi.defaultlight' ...
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = ... Done!
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = ... Done!
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyGlobalDefaultStylesheet -> :INFO = Found global default style sheet. Adding ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loading profiles ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loaded all profiles!
> [pool-2-thread-1] :: com.stream_pi.client.connection.Client$1 @ call -> :INFO = Trying to connect to server at [my server local ip:port]
> [pool-2-thread-1] :: com.stream_pi.client.controller.Controller @ handleMinorException -> :SEVERE = Unable to connect to server. Please check settings and connection and try again.
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = Applying default theme ...
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = Applying theme 'com.stream_pi.defaultdark' ...
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyTheme -> :INFO = ... Done!
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyDefaultTheme -> :INFO = ... Done!
> [JavaFX Application Thread] :: com.stream_pi.client.window.Base @ applyGlobalDefaultStylesheet -> :INFO = Found global default style sheet. Adding ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loading profiles ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loaded all profiles!
> [JavaFX Application Thread] :: com.stream_pi.client.controller.ScreenSaver @ <init> -> :INFO = Is Rpi Screen detected ? true
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loading profiles ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loading profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e ...
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Actions Size : 0
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfile @ load -> :INFO = Loaded profile 6fe15d84-8ac7-4b72-88f6-e497335fea7e (Default Profile) !
> [JavaFX Application Thread] :: com.stream_pi.client.profile.ClientProfiles @ loadProfiles -> :INFO = Loaded all profiles!
> [JavaFX Application Thread] :: com.stream_pi.client.controller.Controller @ onCloseRequest -> :INFO = Shut down
> ```
> 
> _It worked!_ A slider to adjust the brightness is always welcome, but a one time command like so is enough for me. (You can close the issue I think.)
> 
> ```shell
> pi@smartipi2:~ $ cat /sys/class/backlight/rpi_backlight/brightness
> 255
> pi@smartipi2:~ $ echo 100 | sudo tee /sys/class/backlight/rpi_backlight/brightness
> 100
> ```

The problem is that there is no way (atleast that I know of) to know the hardware revision of the pi official screen via software. Older pi lcds didn't support brightness at all.
