### ISSUE TITLE
Console mode not working on Raspberry Pi 2B+

### ISSUE THREAD

**Issue by Icysnowman** [stream-pi/client#92]
Having an issue with launching stream pi in terminal mode it keeps failing to launch using card1. Is your KMS driver turned on? 
i go into sudo raspi-config and select.
G1 Legacy (default) no work as i assume?
G2 GL (fake KMS) no work
G3 GL (full KMS) no work either.
I have tried GPU memory at 128 and 256 neither work.
What am i missing?

**Comment by rnayabed** [comment]
Which raspberry pi are you using?

can you send the output of `ls -l /dev/dri` with 3 of these configurations ?

**Comment by Icysnowman** [comment]
I am using the raspberry pi 2 B+

pi@raspberrypi:~ $ ls -l /dev/dri
total 0
drwxr-xr-x 2 root root         80 Oct 18 16:57 by-path
crw-rw---- 1 root video  226,   0 Oct 18 16:57 card0
crw-rw---- 1 root render 226, 128 Oct 18 16:57 renderD128

**Comment by rnayabed** [comment]
The JavaFX was updated recently in snapshot builds. Can you once try the snapshot arm32 build ?

**Comment by Icysnowman** [comment]
Ok i have been able to get to the shops and purchase a new SD card to try this on and still no luck sorry it has taken so long i did not want to brake the desktop client of it as i have that running but i can not get the terminal one to work still the same error is it possible i am using the wrong os? i am just using the Raspberry Pi imager and selecting Raspberry PI OS Lite 32bit and it still isnt working. Using the fresh image i run `sudo apt  update` followed by `sudo apt full-upgrade` then i restart and run `curl -sSL https://install.stream-pi.com/client/raspberry-pi | bash` once it reboots i run `sudo raspi-config` and enable KMS restart then `~/stream-pi-client/run_console` and it returns that error. 
The first time i spent about 10 hours trying to get it to work before settling on the desktop version.
Today i have spent about another 4 with googling and trying different things but i can not get the console version to work.

**Comment by rnayabed** [comment]
> Ok i have been able to get to the shops and purchase a new SD card to try this on and still no luck sorry it has taken so long i did not want to brake the desktop client of it as i have that running but i can not get the terminal one to work still the same error is it possible i am using the wrong os? i am just using the Raspberry Pi imager and selecting Raspberry PI OS Lite 32bit and it still isnt working. Using the fresh image i run `sudo apt update` followed by `sudo apt full-upgrade` then i restart and run `curl -sSL https://install.stream-pi.com/client/raspberry-pi | bash` once it reboots i run `sudo raspi-config` and enable KMS restart then `~/stream-pi-client/run_console` and it returns that error. The first time i spent about 10 hours trying to get it to work before settling on the desktop version. Today i have spent about another 4 with googling and trying different things but i can not get the console version to work.

Send output of `cat /boot/config.txt`

**Comment by Icysnowman** [comment]
`# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
#dtoverlay=vc4-fkms-v3d
gpu_mem=256
[all]
dtoverlay=vc4-kms-v3d
core_freq=250
sdram_freq=400
over_voltage=0
`

**Comment by rnayabed** [comment]
@Icysnowman 

`dtoverlay=vc4-kms-v3d`

That's the issue. Apparently the normal KMS driver from the Pi foundation does not work well and is broken.

Comment/remove that line and instead put 

`dtoverlay=vc4-fkms-v3d`

line. This turns on the FAKE KMS driver, that although the name may suggest something different, is the one we are looking for.

So your final `config.txt` should be the following:

```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
dtoverlay=vc4-fkms-v3d
gpu_mem=256
core_freq=250
sdram_freq=400
over_voltage=0

```

**Comment by rnayabed** [comment]
Also, please tell which screen are you using. We have found some screens to be not be compatible at all with Raspberry Pi KMS due to the way they are designed by the manufacturer. But most of the time thats not the case.

**Comment by Icysnowman** [comment]
It is a raspberry pi 7" touch screen it works when running the desktop version of it just not the console so i assume its ok? let me know if you need more information on the display?

**Comment by rnayabed** [comment]
> It is a raspberry pi 7" touch screen it works when running the desktop version of it just not the console so i assume its ok? let me know if you need more information on the display?

Did you try using the above method I said?

**Comment by rnayabed** [comment]
@Icysnowman ?

**Comment by Icysnowman** [comment]
I am not home today i will try tomorrow ill be home 20-24 hours from now

**Comment by Icysnowman** [comment]
i tried it with your config and no difference in outcome same error

**Comment by rnayabed** [comment]
> i tried it with your config and no difference in outcome same error

Send your bootconfig again and also the output of `ls -l /dev/dri`

**Comment by Icysnowman** [comment]
Boot Config
```
# For more options and information see
# http://rpf.io/configtxt
# Some settings may impact device functionality. See link above for details

# uncomment if you get no picture on HDMI for a default "safe" mode
hdmi_safe=1

# uncomment this if your display has a black border of unused pixels visible
# and your display can output without overscan
#disable_overscan=1

# uncomment the following to adjust overscan. Use positive numbers if console
# goes off screen, and negative if there is too much border
#overscan_left=16
#overscan_right=16
#overscan_top=16
#overscan_bottom=16

# uncomment to force a console size. By default it will be display's size minus
# overscan.
#framebuffer_width=1280
#framebuffer_height=720

# uncomment if hdmi display is not detected and composite is being output
hdmi_force_hotplug=1

# uncomment to force a specific HDMI mode (this will force VGA)
#hdmi_group=1
#hdmi_mode=1

# uncomment to force a HDMI mode rather than DVI. This can make audio work in
# DMT (computer monitor) modes
#hdmi_drive=2

# uncomment to increase signal to HDMI, if you have interference, blanking, or
# no display
config_hdmi_boost=4

# uncomment for composite PAL
#sdtv_mode=2

#uncomment to overclock the arm. 700 MHz is the default.
arm_freq=800

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Uncomment this to enable infrared communication.
#dtoverlay=gpio-ir,gpio_pin=17
#dtoverlay=gpio-ir-tx,gpio_pin=18

# Additional overlays and parameters are documented /boot/overlays/README

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

[pi4]
# Enable DRM VC4 V3D driver on top of the dispmanx display stack
#dtoverlay=vc4-fkms-v3d
max_framebuffers=2

[all]
dtoverlay=vc4-fkms-v3d
gpu_mem=256
core_freq=250
sdram_freq=400
over_voltage=0
```
ls -l /dev/dri
```
total 0
drwxr-xr-x 2 root root         80 Nov  4 12:25 by-path
crw-rw---- 1 root video  226,   0 Nov  4 12:25 card0
crw-rw---- 1 root render 226, 128 Nov  4 12:25 renderD128

```

**Comment by rnayabed** [comment]
It looks like I will have to personally test this on a Raspberry Pi 2B+. Unfortunately they are hard to come by and are discontinued.

Can you provide the exact link/model name of your display? There are a few screens like ones by HyperPixel that do not play well with Linux KMS/Framebuffer.

**Comment by Icysnowman** [comment]
the screen is a  generic 7" touch https://www.ebay.com.au/itm/202293509636 purchased it back in October 2019 maybe it is similar to the HyperPixel one?

**Comment by rnayabed** [comment]
Its weird that you have a 7 inch screen, yet your boot config does not have any mention of the resolution, etc. How did you set up your screen?

**Comment by Icysnowman** [comment]
it is 1080p and i just turned the pi on and it worked?

**Comment by rnayabed** [comment]
What worked? Stream-Pi?

**Comment by Icysnowman** [comment]
the screen i turned raspbian on after enabling hdmi in the boot config 
```
# uncomment if you get no picture on HDMI for a default "safe" mode
hdmi_safe=1
```
and it turned on and showed the bootup text and all that

**Comment by rnayabed** [comment]
Please provide a picture of the screen running with raspbian fully loaded

**Comment by Icysnowman** [comment]
![20211109_232841](https://user-images.githubusercontent.com/48984022/140924640-9e55eb72-82e9-4c5a-bc8e-864149bde2df.jpg)
This is it turning on then once it is on it goes blue. The blue screen after startup was after installing the stream-pi so i assume it is related to that error i am getting.

**Comment by rnayabed** [comment]
I doubted your screen was not configured properly, and I was right. 

Put the following at the end of your `/boot/config.txt`

```
max_usb_current=1
hdmi_group=2
hdmi_mode=87
hdmi_cvt 1024 600 60 6 0 0 0
hdmi_drive=1
```

Disable/Comment the `hdmi_safe` entry that you created.

**Comment by rnayabed** [comment]
After that, restart your pi and see if the screen works correctly or not. Send a picture too

**Comment by Icysnowman** [comment]
![20211110_215326](https://user-images.githubusercontent.com/48984022/141100595-4a862c77-93f8-48f9-a92f-d9c74abf3b4c.jpg)
The screen is working how it was before the streampi was installed but still have that error when trying to launch console `~/stream-pi-client/run_console`

**Comment by rnayabed** [comment]
At this point I have no idea why its not working. Perhaps you should try reinstalling latest version of pi is from scratch and try again with the 1.0.0 ea+3

**Comment by rnayabed** [comment]
Any updates @Icysnowman ? Are you still using Stream-Pi ? desktop mode/console mode? or did you leave us?

**Comment by rnayabed** [comment]
@Icysnowman try once with the latest snapshot for the client. you can download it via:

```
curl -sSL https://install.stream-pi.com/client/raspberry-pi | bash -s -- -d https://github.com/stream-pi/client/releases/download/1.0.0-EA%2B4-SNAPSHOT/stream-pi-client-linux-arm32-1.0.0-EA+4-SNAPSHOT-executable.zip
```

After that try again and report back. It has much better KMS detection technique.

**Comment by rnayabed** [comment]
Closing it as the issue should be fixed + Issue author has not talked in a while. re open if issue persists

**Comment by Miniontoby** [comment]
Hi,

I also have the same issue and error message.

I am using the `waveshare35a` dtoverlay. It's an 3.5" Raspberry LCD.
Driver: ILI9486

```
miniontoby@pizero:~/stream-pi-client $ ls -l /dev/dri/
total 0
drwxr-xr-x 2 root root         80 Dec 14 15:18 by-path
crw-rw---- 1 root video  226,   0 Dec 14 15:18 card0
crw-rw---- 1 root render 226, 128 Dec 14 15:18 renderD128
miniontoby@pizero:~/stream-pi-client $ ls -l /dev/fb*
crw-rw---- 1 root video 29, 0 Dec 14 15:18 /dev/fb0
crw-rw---- 1 root video 29, 1 Dec 14 15:18 /dev/fb1
miniontoby@pizero:~/stream-pi-client $
```

I can use /dev/fb1 to control what's on the screen.
`cat /dev/random > /dev/fb1` will show random pixels on the screen.

You can actually show real images and text on the display, tho.
I was able to do it with pygame, by drawing to an `pygame.Surface` and then using the `.convert(16,0).get_buffer()` on that Surface and writing the output of that to `/dev/fb1`

I was able to use stream-pi with the desktop version, but pi zero is very slow, so I don't want to do that.

Please help me get the console version to work.
