### ISSUE TITLE
Rotation on Android 12 Equals black screen

### ISSUE THREAD

**Issue by CassTG** [stream-pi/client#99]
Running the latest server (osx) and Android client builds as available on 25th Nov.

If i rotate the Samsung s21 Ultra from portrait to landscape the screen goes black and nothing is displayed. I can see in the server side the layout change to landscape.

If i rotate back to portrait then the deck re appears.

S21 is running latest Android 12 OneUi 4

**Comment by rnayabed** [comment]
Is it possible to try running the client directly in landscape mode from the app launcher?

**Comment by rnayabed** [comment]
This issue should no longer persist with newest builds. There was a bug in the build from 25th nov.

**Comment by CassTG** [comment]
Yep works fine now thanks
